
trigger:
- '*'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Package'
    steps:
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)/drop'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/drop'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Run Python Tests'
    steps:
    - script: |
        pip install pytest pytest-cov flask mysql-connector
        pip install pymysql
        pip install HTMLTestRunner-Python3
      displayName: 'Install modules'
    - script: |
        cd $(Build.Repository.LocalPath)
        python -m pytest -v $(Build.Repository.LocalPath)/*test.py --cov=my_module --junitxml=test-unit.xml
      displayName: 'Run Unit Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-unit.xml'
      condition: always()