#IMPORTANT WORKING
#trigger:
#- '*'
#
#pool:
#  vmImage: ubuntu-latest
#
#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
#- task: CopyFiles@2
#  inputs:
#    targetFolder: '$(Build.ArtifactStagingDirectory)'
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'



trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade Pip'

- script: |
    python -m pip install -r requirements.txt
    # Replace 'requirements.txt' with the actual file containing your dependencies
  displayName: 'Install Dependencies'

- script: |
    cat user_handling_test.py  # Print the content of user_handling_test.py
  displayName: 'Print user_handling_test.py'

- script: python -m unittest user_handling_test.py
  displayName: 'Run Python Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test_results.xml' # Replace with the correct path to your test results file
    testRunTitle: 'Python Tests'
    testRunSystem: 'Python unittest'
