# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Run Python Tests'
    steps:
    - script: |
        pip install pytest pytest-cov flask mysql-connector
        pip install pymysql
        pip install HTMLTestRunner
        pip install unittest
      displayName: 'Install modules'
    - script: |
        cd $(Build.Repository.LocalPath)
        python -m pytest -v $(Build.Repository.LocalPath)/*test.py --cov=my_module --junitxml=test-unit.xml
      displayName: 'Run Unit Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-unit.xml'
      condition: always()

