trigger:
- '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo 'Hello, world!'
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Run Python Tests'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: python -m pip install --upgrade pip
      displayName: 'Upgrade Pip'

    - script: |
        python -m pip install -r requirements.txt
        # Replace 'requirements.txt' with the actual file containing your dependencies
      displayName: 'Install Dependencies'

    - script: |
        python -m pip install nose2 nose2[plugins]
      displayName: 'Install nose2 and plugins'

    - script: |
        python -m nose2 -v
      displayName: 'Run Python Tests with nose2'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'junit.xml'
        testRunTitle: 'Python Tests'
        testRunSystem: 'nose2'



